import React, { useState, useEffect } from "react";
import Head from "next/head";
import axios from "axios";

import shuffle from "../lib/shuffle";
import removeDuplicates from "../lib/removeDuplicates";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import PreviewTextViewer from "../components/PreviewTextViewer";
import Procrastinator from "../components/Procrastinator";

export default function browse() {
  const [retrieved, setRetrieved] = useState(false);
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    const method = async () => {
      if (!retrieved) {
        //Call Backend Endpoint
        const res = await axios.get("/api/posts");

        //Set Unanswered
        const unansweredBuffer = [];

        //Remove Elements after 10
        for (let i = 0; i < res.data.unanswered.length; i++) {
          const question = res.data.unanswered[i];
          i <= 8 && unansweredBuffer.push(question);
        }

        //Shuffle Array
        const newShuffledUnanswered = shuffle(unansweredBuffer);

        //Shuffle All Array
        const shuffledAll = shuffle(res.data.all);

        //Create new Array
        const newArray = [...newShuffledUnanswered, ...shuffledAll];

        setPosts(removeDuplicates(newArray));
        setRetrieved(true);
      }
    };

    method();
  }, []);

  return (
    <div className="bg" style={{ minHeight: "100vh" }}>
      <Head>
        <title>Browse Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {retrieved ? (
        <>
          <h1 className="heading">Browse</h1>
          <h2 className="subhead">These Problems need Solutions</h2>

          <div className="cards">
            {posts.map((post, index) => (
              <>
                <PreviewTextViewer post={post} key={index} />
              </>
            ))}
          </div>

          <Footer />

          <style jsx>
            {`
              .heading {
                font-family: var(--mainfont);
                text-align: center;
                font-weight: 300;
                font-size: 40px;
              }

              .subhead {
                text-align: center;
                font-weight: 400;
                font-size: 1em;
                font-family: var(--mainfont);
              }

              .cards {
                display: flex;
                justify-content: center;
                flex-wrap: wrap;
              }
            `}
          </style>
        </>
      ) : (
        <>
          <br />
          <br />
          <Procrastinator />
        </>
      )}
    </div>
  );
}
